### ISSUE TITLE
npx sandbox doesn't seem to be working

### ISSUE THREAD

**Issue by html5cat** [arc-repos/arc.codes#15]
The process gets stuck on `✓ Started Dynalite DynamoDB`

**Comment by brianleroux** [comment]
just tested on a trivial app / fresh app and seems ok. the step after that is copies src/shared into ALL src/**/*/node_modules/architect/shared which can be slow is /src/shared is really big

can you share the code causing the issue?

**Comment by html5cat** [comment]
I was trying to run it on arc.codes repo to have the docs offline 😊

**Comment by brianleroux** [comment]
lol wow geez! ok… lemme see…

**Comment by brianleroux** [comment]
just updated to latest workflows and didn't reproduce on my machine; can you give it another try?

**Comment by html5cat** [comment]
Works like a charm with latest workflows!
