### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/arc.codes#30]
Currently arc.codes is probably one of the first markdown based serverless CMS systems. So it is pretty raw (and almost silly simple). 

All the content is in [https://github.com/arc-repos/arc.codes/tree/master/src/shared/en/aws](src/shared/en/aws). New translations should use their language code and in a new folder under shared. (Eg src/shared/pt-br, src/shared/es, src/shared/fr, etc)

> Things we need to think about of the top of my head! I am in no way an i18n expert and def appreciate feedback for improving this. 

I have three goals: 

1. Supporting a new language should be as easy as writing markdown
2. The website content needs to be fully URL addressable by language so copy/paste always works
3. Everything remains completely backwards compatible

TODO

- [ ] Add one new route `get /:language/:section/:doc` and make it smart enough to load the right thing from the right place at the right time ;)
- [ ] Make a drop down for selecting a different language in the master layout https://github.com/arc-repos/arc.codes/blob/master/src/shared/render.js (which just redirects to the appropriate url)

---

(cc @ryanblock @kristoferjoseph @rdela and @GustMartins)

**Comment by kborchers** [comment]
Just to throw a wrench into automation of i18n/translations 😉, I would say the design should allow for easily "flipping" to support languages written right to left. I would imagine you can do this with a separate or additional style sheet and when a RTL language is added there should somewhere to flag it as such.

**Comment by brianleroux** [comment]
closing for now…hopefully we hear back again!
