### ISSUE TITLE
Location of static assets described differently in different sections

### ISSUE THREAD

**Issue by filmaj** [arc-repos/arc.codes#45]
In the static guide (https://arc.codes/guides/static-assets):

> To support this, every .arc project is set up with a public directory in the root of your project. The public directory provides a seamless way to work with static assets such as images, styles, and scripts required in your front-end workflows.

In the `@static` reference (https://arc.codes/reference/static):

> Locally, if the hidden folder /.static exists, whenever you run npx deploy the contents are synchronized to the staging bucket. If you set ARC_DEPLOY=production the contents of /.static are deployed to the production bucket. This allows the frontend dev to use whatever build tooling they like (ParcelJS, Webpack, Browserify, Babel, etc).

So, is it `public/` dir, or `.static` dir?

**Comment by brianleroux** [comment]
good catch, thank you. `/public` for future reference!
