### ISSUE TITLE
export issue

### ISSUE THREAD

**Issue by cristianexer** [arc-repos/arc.codes#63]
Probably I've imported it wrong but it seems that if I am not using the arc.middleware function is working.

```
src/shared/middleware/auth.js

const jwt = require('jsonwebtoken');
let arc = require("@architect/functions");
const util = require('@architect/shared/helpers/util');

async function auth(req, res, next) {
    if (!req.headers.authorization)
        res(util.response({
            response: `Missing authorization`
        }, 'json', 400));

    let authorized = await jwt.verify(req.headers.authorization, process.env.APP_SECRET || 'secretKey');
    if (authorized) {
        next();
    } else {
        res(util.response({
            response: `Invalid token`
        }, 'json', 400));
    }

}
//typeof arc.middleware(auth) => function
exports.handler = arc.middleware(auth); // here I've replaced with auth
```

```
src/http/post-win/index.js

let arc = require('@architect/functions');
let auth = require('@architect/shared/middleware/auth');

// typeof auth => object
// also the object is empty

async function win(res){
console.log("works"); // here I've commented all the logic.
}

exports.handler = arc.http(auth, win); // arc.http does not accept objects
````

Basically I've followed the example with routes but I am pretty sure it's an importing error.

Also what are the benefits of arc.middleware ?

**Comment by brianleroux** [comment]
hey ! sorry for the confusion you want to use `arc.http()` with that first example. I'll let @mikemaccana answer your second q tho!

**Comment by mikemaccana** [comment]
> arc.middleware(auth);

Arc middleware combines multiple route lambdas into one - there's no point using it with a single function! See https://arc.codes/reference/middleware

> exports.handler = arc.http(auth, win);

This should be `exports.handler = arc.middleware(auth, win);`Check the `requireLogin` example at https://arc.codes/reference/middleware for an equivalent of your `auth` function.

**Comment by mikemaccana** [comment]
PS @cristianexer Check out https://github.com/mikemaccana/arc-example-login-flow, which uses the new API and will soon be merged into the mainline arc (see https://github.com/arc-repos/arc-example-login-flow/pull/6)

**Comment by brianleroux** [comment]
Going to close this issue but feel free to reopen if more discussion required!
