### ISSUE TITLE
middleware guide is not linked from left menu

### ISSUE THREAD

**Issue by filmaj** [arc-repos/arc.codes#64]
this one: https://arc.codes/reference/middleware

**Comment by brianleroux** [comment]
it is but you gotta scroll to find it
<img width="1141" alt="screen shot 2019-01-09 at 10 05 49 am" src="https://user-images.githubusercontent.com/990/50918878-3abf2a00-13f6-11e9-973f-8c91be7fc97c.png">

**Comment by filmaj** [comment]
Fuck me. Closing, feeling quite ashamed 🙈

**Comment by mikemaccana** [comment]
Maybe it would be better as a 'guide' (at the top) rather than a 'reference'? It's so small it doesn't need long documentation, so probably 'guide' would be a better fit.
