### ISSUE TITLE
Middleware guide example doesn't work in unauthenticated scenario

### ISSUE THREAD

**Issue by filmaj** [arc-repos/arc.codes#69]
I'm not sure if this is a recent regression or not w/ architect, and if I'm filing in the right place. I'll file here and can always copy over to the right repo.

The middleware guide (https://arc.codes/reference/middleware) has a pretty standard authentication middleware:

```
// Redirect if the user isn't logged in
async function requireLogin(req) {
    let state = await arc.http.session.read(req);

    if (!state.isLoggedIn) {
        console.log(`Attempt to access dashboard without logging in!`);
    return {
      status: 301,
      location: `/login`
    };
    }
    console.log(`We're logged in`);
    // return nothing, so middleware continues
}
```

My own arc-example-auth middleware is along the same lines:

```
let arc = require('@architect/functions');
let url = arc.http.helpers.url;

module.exports = async function auth (req) {
    let session = await arc.http.session.read(req);
    // if the current session is not logged in boot back to homepage
    if (!session || !session.account) {
        return {
            status: 302,
            cookie: await arc.http.session.write(req),
            location: url('/')
        };
    }
};
```

However what I see when I try to load any page that's behind the above middleware (using `npx sandbox`), not having logged in, is the following page:

<img width="931" alt="screen shot 2019-01-12 at 8 25 18 am" src="https://user-images.githubusercontent.com/52645/51074334-a21de980-1643-11e9-9fda-7130041d2daa.png">

Note that I see no errors in the terminal where I'm running `npx sandbox`.

After commenting out some stuff, it looks to be based on the `session.write` call.

I'm digging in right now and deep into the arc-functions codebase and having a tough time nailing down where this is coming from, to be honest. Will report back with more as I keep exploring.

**Comment by filmaj** [comment]
Fuck, nevermind, I'm a fkn idiot. I'm writing the request object to the session 🤦‍♂️ of course only after typing this all out and spending an hour investigating that I realize a) writing to the session in the first place is stupid in the auth middleware and b) im writing the wrong object.

jeeeesus fil wtf

**Comment by brianleroux** [comment]
all good! wondering…how could we make this easier / what would have you expected ?

**Comment by filmaj** [comment]
One thing I think that could help is to use a consistent style on the docs/guides. I noticed some examples use the old `arc.http` route helper, which requires the use of a `res()` function to return a response, whereas others (like the middleware guide) don't use that and rely on `return`ing response objects directly.
