### ISSUE TITLE
How can I get S3 to use correct MIME types for static content?

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/arc.codes#73]
**This is probably a documentation issue**. As in, I don't understand how to do something and the [current static docs](https://arc.codes/guides/static-assets) don't tell me.

## Quick question

**Minor note**: the [docs](https://arc.codes/guides/static-assets) don't cover this, but since S3 [doesn't have 'real' folders](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/using-folders.html) (and looking at the other arc-examples), I guess `/static` should be flat and not have folders (folders do work on sandbox though, which is why I'm confused). Is that correct?

## Issue

Source code: https://github.com/arc-repos/arc-example-notes, using arc 4.5.6

On sandbox:

![image](https://user-images.githubusercontent.com/172594/51488028-64843380-1d9c-11e9-814b-4cd68bc5deca.png)

On staging:

![image](https://user-images.githubusercontent.com/172594/51488002-5209fa00-1d9c-11e9-8b1a-7df449ac27f9.png)

CORB error:

![image](https://user-images.githubusercontent.com/172594/51488174-c0e75300-1d9c-11e9-91dd-817786b65174.png)

Edit: Note this is CORB not CORS.

**Comment by mikemaccana** [comment]
Oooh wait this is CORB not CORS....

**Comment by mikemaccana** [comment]
From reading https://www.chromium.org/Home/chromium-security/corb-for-developers it looks like the MIME type being sent incorrectly from S3 is causing the issue.

**How can I get S3 to use correct MIME types for static content?**

**Comment by brianleroux** [comment]
Could be a bug w upload code in deploy. You can change mimes in the S3 console. Just walking but will be atta machine shortly

**Comment by mikemaccana** [comment]
Thanks for the quick reply, that would be cool. I'll get into the console now. Am I right that /static has to be flat?

**Comment by brianleroux** [comment]
Nope! Just can't have empty folders is all

**Comment by mikemaccana** [comment]
Yeah it looks like you're right: the deploy code is trying to replicate the entire directory structure on S3:

        ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/:/Users/mikem/OneDrive/Documents/arc-
    example-notes/public/style.css

![image](https://user-images.githubusercontent.com/172594/51489691-f9892b80-1da0-11e9-88a9-b7761c6456df.png)

**Comment by mikemaccana** [comment]
Opening `_copy_to_s3.js` and changing:
 
    var key = file.replace(path.join(process.cwd(), 'public'), '').substr(1)

To:

    var key = file.replace(/.*\/public/, '').substr(1)

And running `npx deploy` returns:

    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/forms.css
    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/cards.css
    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/architect-favicon-32.png
    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/architect-favicon-16.png
    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/fonts.css
    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/style.css
    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/logo.svg
    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/hero.css
    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/nav.css
    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/logo-light.svg
    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/architect-favicon-64.png
    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/readme.md
    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/metrics.css
    ✓ https://s3.us-east-1.amazonaws.com/arc-example-notes-staging/colors.css

Which appear correct. However those files (unlike the ones above) do not appear in the S3 console. Is there some better way to redeploy static than `npx deploy`?

**Comment by mikemaccana** [comment]
Looks like the files just took a moment to appear n S3: 

![image](https://user-images.githubusercontent.com/172594/51491560-a023fb00-1da6-11e9-81ee-ae2ba55394a4.png)

**Comment by mikemaccana** [comment]
Also for my own ref (and maybe yours): https://github.com/nodejs/node/issues/8237

**Comment by brianleroux** [comment]
huh, TIL

**Comment by mikemaccana** [comment]
OK `npx deploy` now pushing files to the correct location on S3 per the PR above.

But content types still aren't being set properly (everything is `application/xml` and gets blocked accordingly by the browser).

Setting content type manually doesn't work either:

![image](https://user-images.githubusercontent.com/172594/51505863-062d7400-1de1-11e9-9008-9b9a461c359b.png)
 
![image](https://user-images.githubusercontent.com/172594/51505965-9c619a00-1de1-11e9-8516-b7ab41815a77.png)

It's getting late here now so can check again in morning, but if you have any ideas re: content types (maybe check out and deploy https://github.com/arc-repos/arc-example-notes) it would be useful.

**Comment by mikemaccana** [comment]
This is resolved (once the PR is merged) now - I wiped and remade the bucket, used the code in the PR to `npx deploy static` and I'm getting the correct MIME types now.

**Comment by mikemaccana** [comment]
It's so pretty 🙂: 

![image](https://user-images.githubusercontent.com/172594/51536916-03646a80-1e45-11e9-9b3d-36a15560a62f.png)

**Comment by mikemaccana** [comment]
Actually going to close this anyway since it's for the wrong repo.
