### ISSUE TITLE
[Feedback wanted] more consistent approach to topics

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/arc.codes#77]
Right now, for example **Static** is covered in:

 - https://arc.codes/guides/http (overview)
 - https://arc.codes/guides/static-assets (overview)
 - https://arc.codes/reference/static (full reference

Some things that could be done better:
 - 1 and 2 are really similar - when we update either, we need to update both. 
 - `http` is getting long. 
 - It's hard to work out whether the overview should be in the `http` guide or the `static-assets` guide.

I **feel** like maybe we can skip the first - the intros in the `http` guide cover a bit too much, and should link to the guides.

What does everyone else think?

**Comment by brianleroux** [comment]
Agree, zooming out a bit I think a reorg could help:
- **Quickstart** is the highest level overview 
- **Guides** should be a walk through of a specific topic area
- **Reference** should be straight up reference material

To me HTTP functions, Static Assets, CORs and Single Page Apps are specific topic areas. (And all could be written better.) But probably fine as *Guides**. Maybe we need to enhance the quickstart content with a high level overview of the web dev/sever features of architect?

**Comment by mikemaccana** [comment]
Right now quickstart shows the basics, then goes straight into the HTTP guide

We could add a 4th bit to quickstart which is exactly that - a high level overview of the web dev/sever features of architect?

---
`https://arc.codes/quickstart/arc-project-layout`

## What to do next?

Add [lambdas](/guides/http) - these will be the basic routes of your app

Use [sessions](/guides/sessions) - arc comes with inbuilt, fast sessions thanks to DynamoDB

Use [middleware](/guides/middleware) - middleware allows you to combine routing logic, and is useful for checking if a user is logged in, adding extra information to the request, or other tasks.

[Share code](/guides/sharing-common-code) between your lambdas

Add [background tasks](/guides/background-tasks) - `@events` allows you to do offline work, and is useful for splitting up larger tasks into smaller ones

(etc)
---

And move/combine the extra content in /guides/http for things that aren't HTTP  (eg, Sessions, Code Sharing, etc) into their respective guides.

**Comment by brianleroux** [comment]
I like that
