### ISSUE TITLE
How to exclude development dependencies from deployment?

### ISSUE THREAD

**Issue by alexbepple** [arc-repos/arc.codes#79]
After I added Mocha to my development dependencies, the code size of the deployed lambda grew. What is the proper way to exclude development dependencies from being included in the bundle?

**Comment by brianleroux** [comment]
you should add dev deps to the root package.json and not to anything in `src/*`

is this what you did ? (lambdas include deps from their own package.json files as well as anything in src/shared or src/views)

**Comment by alexbepple** [comment]
@brianleroux Yes, I added the unit-test deps to the `src/events/xyz/package.json`. Moving them to the root `package.json` worked out fine. Thanks for pointing this out. I think it would be helpful to mention this somewhere. Maybe a mini-guide to unit-testing?
