### ISSUE TITLE
Error when running `npx deploy` with VS Code open

### ISSUE THREAD

**Issue by neilhoff** [arc-repos/arc.codes#86]
If I have the project open in Visual Studio Code and then run `npx deploy` I get this error:

```
npm ERR! path C:\Users\...\src\http\get-index\node_modules
  npm ERR! code EPERM
  npm ERR! errno -4048
  npm ERR! syscall stat
  npm ERR! Error: EPERM: operation not permitted, stat 'C:\Users\...\src\http\get-index\node_modules'
  npm ERR!  { Error: EPERM: operation not permitted, stat 'C:\Users\...\src\http\get-index\node_modules'

```

It looks like it is unable to delete the node_modules directory.

Once I close VS Code and re-run `npx deploy` it works great.

I am using Cmder on Windows 10.

**Comment by neilhoff** [comment]
Of course...a reboot fixed it.

**Comment by brianleroux** [comment]
awesome, that's the best! (windows support super important to us so also thank you for reporting 🙏)
